Update CI

diff --git a/.github/workflows/CI Pipeline.yml b/.github/workflows/CI Pipeline.yml
--- a/.github/workflows/CI Pipeline.yml
+++ b/.github/workflows/CI Pipeline.yml
@@ -28,4 +28,15 @@ jobs:
 
     - name: Build solution
       run: dotnet build --no-restore --configuration Release
-        
+      
+    - name: Debug: Ensure test DLL exists
+      run: |
+        if [ ! -f "/home/runner/work/Final-Task/Final-Task/Trenning_NotificationsExample.Tests/bin/Debug/net8.0/Trenning_NotificationsExample.Tests.dll" ]; then
+          echo "Test DLL not found!"
+          exit 1
+        else
+          echo "Test DLL exists."
+        fi 
+            - name: Run tests 
+    - name: Run tests
+      run: dotnet test Trenning_NotificationsExample.Tests/Trenning_NotificationsExample.Tests.csproj --no-build --verbosity normal
